### PR TITLE
Support for Indian phone numbers

### PR DESCRIPTION
**Pull request by Livin21**
Added support for indian phone numbers

### CODE REVIEW

**Comment by tunnckoCore** [comment]
Looks good to me, @johnotander thoughts? _Seems like i can ping only you of all the commiters (sindre and arthur) ;d don't ask why._

@jonschlinkert does the regex feels good, you-guru-man? :cake: :laughing:

**Review by tunnckoCore — APPROVED** [review]

**Review by tunnckoCore — APPROVED** [review]
LGTM!

**Comment by Livin21** [comment]
@johnotander just a reminder :)

**Comment by johno** [comment]
Lgtm. Won't be at my computer today to publish, perhaps @charlike can bump
a minor and publish?

**Comment by tunnckoCore** [comment]
I can merge and tag it, but can't publish since i don't have npm rights for it :)

**Comment by johno** [comment]
Added you as an owner 💖

**Comment by tunnckoCore** [comment]
Great. I'll release minor bump.

**Comment by tunnckoCore** [comment]
Done! :)

**Pull request merged**
